name: condaenv
channels:
  - conda-forge
dependencies:
  - cachetools=5.2.1
  - cloudpickle=2.1.0
  - cryptography=38.0.4
  - cudatoolkit=11.2
  - cudatoolkit-dev=11.2
  - datasets=1.18.3
  - dm-haiku=0.0.8
  - filelock=3.3.1
  - functorch=0.2.1
  - eigen=3.4.0
  - fuzzywuzzy=0.18.0
  - gensim=3.8.3
  - gmpy2=2.1.2
  - graph-tool=2.45
  - hyperopt=0.2.7
  - imbalanced-learn=0.10.0
  - jax=0.3.20
  - jaxlib=0.3.20=cuda112py39*
  - keras=2.10.0
  - lightgbm=3.1.1
  - loguru=0.6.0
  - mkl=2022.1.0
  - mmh3=3.0.0
  - networkx=2.8.8
  - nltk=3.8.1
  - numba=0.56.2
  - numpy=1.23.3
  - opacus=1.2.0
  - optax=0.1.3
  - pandas=1.4.4
  - pip=22.2.2
  - phe=1.5.0
  - pycryptodome=3.16.0
  - pycryptodomex=3.16.0
  - pynacl=1.5.0
  - pytest=7.1.3
  - python=3.9.13
  - python-duckdb=0.6.1
  - python-igraph=0.10.2
  - python-lmdb=1.3.0
  - python-xxhash=2.0.2
  - pytorch-gpu=1.12.1=cuda112py39*
  - pytorch-lightning=1.7.6
  - pytorch_geometric=2.2.0
  - ray-tune=1.6.0
  - rsa=4.7.2
  - ruamel.yaml=0.17.21
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - tensorflow-gpu=2.10.0=cuda112py39*
  - tokenizers=0.10.3
  - torchmetrics=0.11.0
  - tqdm=4.64.1
  - transformers=4.8.2
  - xgboost=1.7.1=cuda112py39*
  - pip:
      - apsw==3.9.2-r1
      - flwr[simulation]==1.1.0
      - gower==0.1.2
      - interpret==0.3.0
      - peewee==3.10.0
      - protobuf==3.20.3
      - git+https://github.com/ibarrond/Pyfhel.git@0dee7a77469627c4de4f2dca97cdc68bf006a77d
      - py-polar-codes==1.2.2
      - python-dp==1.1.1
      - tensorflow_privacy==0.7.3
      - tensorflow-probability==0.15.0
      - deepwalk==1.0.3
