name: build

on:
  push:
    branches: [main]
    paths: ["runtime/**", ".github/workflows/build-images.yml"]
  pull_request:
    paths: ["runtime/**", ".github/workflows/build-images.yml"]
  workflow_dispatch:

jobs:
  build:
    name: Build, Test, and Publish Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        proc: ["cpu", "gpu"]
    env:
      LOGIN_SERVER: petsprize.azurecr.io
      IMAGE: petsprize-competition
      SHA_TAG: ${{ matrix.proc }}-${{ github.sha }}
      LATEST_TAG: ${{ matrix.proc }}-latest
      PUBLISH_IMAGE: ${{ secrets.PUBLISH_IMAGE }}

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build runtime \
            --build-arg CPU_OR_GPU=${{ matrix.proc }} \
            --tag $LOGIN_SERVER/$IMAGE:$SHA_TAG \
            --tag $LOGIN_SERVER/$IMAGE:$LATEST_TAG

      - name: Check image size
        run: |
          docker image list $LOGIN_SERVER/$IMAGE

      - name: Tests packages in container
        run: |
          docker run --entrypoint /bin/bash $LOGIN_SERVER/$IMAGE:$SHA_TAG \
            -c "conda run --no-capture-output -n condaenv python -m pytest tests"

      - name: Log into Azure
        if: ${{ github.ref == 'refs/heads/main' && env.PUBLISH_IMAGE == '1' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log into ACR with Docker
        if: ${{ github.ref == 'refs/heads/main' && env.PUBLISH_IMAGE == '1' }}
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to ACR
        if: ${{ github.ref == 'refs/heads/main' && env.PUBLISH_IMAGE == '1' }}
        run: |
          docker push $LOGIN_SERVER/$IMAGE --all-tags
